### ISSUE TITLE
You are trying to add a non-nullable field 'date' to wip without a default

### ISSUE THREAD

**Issue by sathapae** [pchaivong/wippie#9]
@pchaivong 
nother new issue :-) 

Below is my code for WIP. When doing the makemigrations, it seems like it need the default value for date. Do you know why I got such an error? I did write the date exactly like you did in holidays.

=========== My Code =======
class WIP(models.Model):
    date = models.DateField()
    new_amt = models.PositiveSmallIntegerField()
    pending_amt = models.PositiveSmallIntegerField ()
    inprogress_amt = models.PositiveSmallIntegerField()

```
def __unicode__(self):
    return "test"
```

============= End of my code =======

Here is the error when I did makemigrations

============= ERROR =======
(env) D:\Python_Tutorial\workspace\wippie\wippie>python manage.py makemigrations
You are trying to add a non-nullable field 'date' to wip without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows)
 2) Quit, and let me add a default in models.py
Select an option:

**Comment by pchaivong** [comment]
I think the root cause is there is already some row in WIP table which doesn't have date value.
There are two ways to fix this.

Hard but proper way

delete file db.sqlite3 and run makemigrations and migrate (and of course, you have to create super user again)

Easy way, but (I think not proper, but I sometimes do it ha ha ha)
change your code to 

date = models.DateField(null=True)

This will allow 'date' column in database to be null

**Comment by sathapae** [comment]
I am a good student...by following the proper way 555. However, deleting db.sqllite3 still doesn't work.

Therefore, I delete all the my env and start all over again.

This time, I add my Wip class in models.py before doing makemigrations and migrate.

I can create Wip Table without any error. However, I cannot see my "Wip" Table when I run "runserver" (http://127.0.0.1:8080/admin/). I can see only Holidays and TS Users Table.

Do you have any idea how to check if my Wip table is really created when running migrate? Please advise :-)

Below is my code.
========= My Code ==========

class Wip(models.Model):
    date = models.DateField()
    new_amt = models.PositiveSmallIntegerField()
    pending_amt = models.PositiveSmallIntegerField ()
    inprogress_amt = models.PositiveSmallIntegerField()

```
def __unicode__(self):
    return "test"
```

**Comment by sathapae** [comment]
More information, when I check fine 001_initial.py, I can see below code. Does it mean that my Wip table is created? I also attach my full file of 001_initial.py.

```
    migrations.CreateModel(
        name='Wip',
        fields=[
            ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ('date', models.DateField()),
            ('new_amt', models.PositiveSmallIntegerField()),
            ('pending_amt', models.PositiveSmallIntegerField()),
            ('inprogress_amt', models.PositiveSmallIntegerField()),
        ],
    ),
```

[0001_initial.txt](https://github.com/pchaivong/wippie/files/19924/0001_initial.txt)

**Comment by pchaivong** [comment]
P' Oun krub,

That file will be created when we run 'makemigrations', the framework will auto-generated that file.
The actual table will be actually created in db when we run 'migrate'

In order to make it visible in admin page, you have to register your model in admin.py krub (api/admin.py).
In the very last line of the file.

You can see how I registered 'Holiday' model in that file (just one line of code)

admin.site.register(<Your Model Class>) # If I remember correctly, but double check the example in that file
However, you will need to import your model.
In the beginning of the file

from .models import <Your Model Class>

**Comment by sathapae** [comment]
It works now !!!!

Thanks a lot krub :)
